#pragma once
#define FILE_DEVICE_CAMERA 40001

#define IOCTL_CAMERA_START_STREAM CTL_CODE(FILE_DEVICE_CAMERA, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_CAMERA_STOP_STREAM CTL_CODE(FILE_DEVICE_CAMERA, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_CAMERA_SET_FRAME CTL_CODE(FILE_DEVICE_CAMERA, 0x802, METHOD_IN_DIRECT, FILE_ANY_ACCESS)
#define IOCTL_CAMERA_GET_FRAME CTL_CODE(FILE_DEVICE_CAMERA, 0x803, METHOD_OUT_DIRECT, FILE_ANY_ACCESS)
#define IOCTL_CAMERA_LOAD_FIRMWARE CTL_CODE(FILE_DEVICE_CAMERA, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)

DEFINE_GUID(GUID_DEVINTERFACE_CAMERA,
    0xcdc35b6e, 0xbe4, 0x4936, 0xbf, 0x5f, 0x55, 0x37, 0x38, 0xa, 0x7c, 0x11);