/*++

Module Name:

    device.c - Device handling events for example driver.

Abstract:

   This file contains the device entry points and callbacks.

Environment:

    Kernel-mode Driver Framework

--*/
#include "driver.h"
#include "device.tmh"
#include "registers.h"
#include "interrupt.h"
#include "public.h"

EVT_WDF_DEVICE_PREPARE_HARDWARE OnEvtDevicePrepareHardware;
EVT_WDF_DEVICE_RELEASE_HARDWARE OnEvtDeviceReleaseHardware;
EVT_WDF_DEVICE_D0_ENTRY OnEvtDeviceD0Entry;
EVT_WDF_DEVICE_D0_EXIT OnEvtDeviceD0Exit;

#ifdef ALLOC_PRAGMA
#pragma alloc_text (PAGE, wdfvpuCreateDevice)
#pragma alloc_text (PAGE, OnEvtDevicePrepareHardware)
#pragma alloc_text (PAGE, OnEvtDeviceReleaseHardware)
#endif

NTSTATUS
wdfvpuCreateDevice(
    _Inout_ PWDFDEVICE_INIT DeviceInit
    )
/*++

Routine Description:

    Worker routine called to create a device and its software resources.

Arguments:

    DeviceInit - Pointer to an opaque init structure. Memory for this
                    structure will be freed by the framework when the WdfDeviceCreate
                    succeeds. So don't access the structure after that point.

Return Value:

    NTSTATUS

--*/
{
    WDF_OBJECT_ATTRIBUTES deviceAttributes;
    PDEVICE_CONTEXT deviceContext;
    WDFDEVICE device;
    NTSTATUS status;
    WDF_PNPPOWER_EVENT_CALLBACKS PnpCallbacks;

    PAGED_CODE();

    WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&deviceAttributes, DEVICE_CONTEXT);

    WDF_PNPPOWER_EVENT_CALLBACKS_INIT(&PnpCallbacks);
    PnpCallbacks.EvtDevicePrepareHardware = OnEvtDevicePrepareHardware;
    PnpCallbacks.EvtDeviceReleaseHardware = OnEvtDeviceReleaseHardware;
    PnpCallbacks.EvtDeviceD0Entry = OnEvtDeviceD0Entry;
    PnpCallbacks.EvtDeviceD0Exit = OnEvtDeviceD0Exit;

    WdfDeviceInitSetPnpPowerEventCallbacks(DeviceInit, &PnpCallbacks);
    status = WdfDeviceCreate(&DeviceInit, &deviceAttributes, &device);

    if (NT_SUCCESS(status)) {
        //
        // Get a pointer to the device context structure that we just associated
        // with the device object. We define this structure in the device.h
        // header file. DeviceGetContext is an inline function generated by
        // using the WDF_DECLARE_CONTEXT_TYPE_WITH_NAME macro in device.h.
        // This function will do the type checking and return the device context.
        // If you pass a wrong object handle it will return NULL and assert if
        // run under framework verifier mode.
        //
        deviceContext = DeviceGetContext(device);

        //
        // Initialize the context.
        //
        deviceContext->PrivateDeviceData = 0;

        //
        // Create a device interface so that applications can find and talk
        // to us.
        //
        status = WdfDeviceCreateDeviceInterface(
            device,
            &GUID_DEVINTERFACE_WDFVPU,
            NULL // ReferenceString
            );

        if (NT_SUCCESS(status)) {
            //
            // Initialize the I/O Package and any Queues
            //
            status = wdfvpuQueueInitialize(device);
        }
    }

    return status;
}



NTSTATUS
OnEvtDevicePrepareHardware (
    _In_ WDFDEVICE Device,
    _In_ WDFCMRESLIST ResourcesRaw,
    _In_ WDFCMRESLIST ResourcesTranslated
    )
/*++

Routine Description:

    EvtDevicePrepareHardware callback handler for the controller FDO.
    It expects Register memory and two interrupts - Device and Wake.

Arguments:

    Device - WDFDEVICE object representing the controller.

    ResourcesRaw - Raw resources relative to the parent bus driver.

    ResourcesTranslated - Translated resources available for the controller.

Return Value:

    Appropriate NTSTATUS value

--*/
{
    NTSTATUS Status;
    ULONG ResCount;
    ULONG ResIndex;
    PDEVICE_CONTEXT ControllerContext;
    BOOLEAN MemoryResourceMapped;

    PAGED_CODE();

    TraceEntry();

    ControllerContext = DeviceGetContext(Device);
    MemoryResourceMapped = FALSE;

    ResCount = WdfCmResourceListGetCount(ResourcesRaw);

    Status = STATUS_SUCCESS;

    for (ResIndex = 0; ResIndex < ResCount; ResIndex++) {

        PCM_PARTIAL_RESOURCE_DESCRIPTOR ResourceDescriptorRaw;
        PCM_PARTIAL_RESOURCE_DESCRIPTOR ResourceDescriptorTranslated;

        ResourceDescriptorRaw = WdfCmResourceListGetDescriptor(
                                                        ResourcesRaw,
                                                        ResIndex);
        switch (ResourceDescriptorRaw->Type) {

        case CmResourceTypeMemory:
            if (MemoryResourceMapped == FALSE) {
                MemoryResourceMapped = TRUE;
                Status = RegistersCreate(Device, ResourceDescriptorRaw);
                //CHK_NT_MSG(Status, "Failed to read the HW registers");
            }
            break;

        case CmResourceTypeInterrupt:
            ResourceDescriptorTranslated = WdfCmResourceListGetDescriptor(
                                                            ResourcesTranslated,
                                                            ResIndex);
            Status = InterruptCreate(
                                Device,
                                ResourceDescriptorRaw,
                                ResourceDescriptorTranslated);
            //CHK_NT_MSG(Status, "Failed to create WDFINTERRUPT object");
            break;

        default:
            break;
        }
    }

    NT_ASSERT(ControllerContext->DeviceInterrupt != NULL);

//End:
    TraceExit();
    return STATUS_SUCCESS;
}


NTSTATUS
OnEvtDeviceReleaseHardware (
  _In_ WDFDEVICE Device,
  _In_ WDFCMRESLIST ResourcesTranslated
    )
/*++

Routine Description:

    EvtDeviceReleaseHardware callback handler for the controller FDO.
    It expects Register memory and two interrupts - Device and Wake.

Arguments:

    Device - WDFDEVICE object representing the controller.

    ResourcesTranslated - Translated resources available for the controller.

Return Value:

    Appropriate NTSTATUS value

--*/
{
    PREGISTERS_CONTEXT RegistersContext;
    PDEVICE_CONTEXT ControllerContext;

    TraceEntry();

    PAGED_CODE();

    UNREFERENCED_PARAMETER(ResourcesTranslated);

    ControllerContext = DeviceGetContext(Device);
    ControllerContext->DeviceInterrupt = NULL;
    ControllerContext->AttachDetachInterrupt = NULL;

    RegistersContext = DeviceGetRegistersContext(Device);
    if ((RegistersContext == NULL) || (RegistersContext->RegisterBase == NULL)) {
        goto End;
    }

    MmUnmapIoSpace(RegistersContext->RegisterBase, RegistersContext->RegistersLength);
    RtlZeroMemory(RegistersContext, sizeof(*RegistersContext));

End:
    TraceExit();
    return STATUS_SUCCESS;
}

NTSTATUS
OnEvtDeviceD0Entry (
  _In_ WDFDEVICE Device,
  _In_ WDF_POWER_DEVICE_STATE PreviousState
)
/*++

Routine Description:

    Called by the framework after entering D0 state.

Arguments:

    Device - WDFDEVICE framework handle to the bus FDO.

    PreviousState - The WDF_POWER_DEVICE_STATE from which the stack is
        making this transition.

Return Value:

    Returns STATUS_SUCCESS or an appropriate NTSTATUS code otherwise.

--*/
{
    UNREFERENCED_PARAMETER(Device);
    UNREFERENCED_PARAMETER(PreviousState);

    return STATUS_SUCCESS;
}

NTSTATUS
OnEvtDeviceD0Exit (
  _In_ WDFDEVICE Device,
  _In_ WDF_POWER_DEVICE_STATE TargetState
    )
/*++

Routine Description:

    Called by the framework when leaving our operational state (D0).

Arguments:

    Device - WDFDEVICE framework handle to the bus FDO.

    TargetState - The WDF_POWER_DEVICE_STATE to which the stack is
        making its transition.


Return Value:

    Returns STATUS_SUCCESS.
    Any failed status code will leave the device stack in failed state and
    device will not get any D0Entry callbacks after that.

--*/
{
    UNREFERENCED_PARAMETER(Device);
    UNREFERENCED_PARAMETER(TargetState);

    return STATUS_SUCCESS;
}
